# Generated by Django 4.2 on 2023-04-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic_police',
            old_name='login_id',
            new_name='login',
        ),
    ]
