# Generated by Django 4.2 on 2023-04-30 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0003_rename_login_id_drivers_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
