# Generated by Django 4.2 on 2023-05-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0006_traffic_blocks_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus_routes',
            old_name='From',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='bus_routes',
            old_name='to',
            new_name='start',
        ),
    ]
