# Generated by Django 4.2 on 2023-05-05 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0007_rename_from_bus_routes_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_allocation',
            old_name='time',
            new_name='arrival_time',
        ),
        migrations.AddField(
            model_name='time_allocation',
            name='departure_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
