# Generated by Django 4.2 on 2023-05-05 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0009_bus_latitude_bus_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='latitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
