# Generated by Django 4.2 on 2023-05-06 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0010_alter_bus_latitude_alter_bus_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
