# Generated by Django 4.2 on 2023-05-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0011_passengers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='passengers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='passengers',
            name='image',
        ),
    ]
