# Generated by Django 4.2 on 2023-05-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0013_feedback_ratings_remove_ratings_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='bus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TrafficApp.bus'),
        ),
    ]
