# Generated by Django 4.2 on 2023-05-15 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0018_traffic_blocks_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic_blocks',
            name='bus_id',
        ),
    ]
