# Generated by Django 4.2 on 2023-05-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrafficApp', '0020_traffic_blocks_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traffic_blocks',
            name='driver_id',
        ),
    ]
